### ISSUE TITLE
How to control the size

### ISSUE THREAD

**Issue by DSPerson** [multiavatar/multiavatar-php#3]
default size is 600 * 600

**Comment by giekaton** [comment]
The size is not fixed to 600x600. I'm not sure where did you get these dimensions.

When used in HTML, it automatically expands to the size of its container, be it 100px or 1000px.

**Comment by DSPerson** [comment]
for example the url is ```https://api.multiavatar.com/default.png```. open it. and size is 600 * 600
<img width="130" alt="截屏2021-02-17 17 48 01" src="https://user-images.githubusercontent.com/17868782/108186392-48ece200-7148-11eb-8f15-7b95fe240888.png">

**Comment by giekaton** [comment]
Correct, but that's the API, not the Multiavatar script. For the API, I have decided to use 600x600 px in order to save traffic, and because this looks like an optimal size for most cases. Currently, it is not possible to change the size of the PNG avatar when generating with the API. 

If you generate SVG format with the API, the size is not fixed, e.g. https://api.multiavatar.com/default.svg

**Comment by giekaton** [comment]
And if you download the PNG file from the avatar's individual page, the PNG size will be 1000x1000 px, try it here: https://multiavatar.com/default

**Comment by DSPerson** [comment]
okkkk Thanks
